openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: /v1
info:
  description: This is the API for the user management and identity provider
  version: "1"
  title: User Management Service
  contact:
    name: Thomas Bonk
    email: thomas@meandmymac.de
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: commands
    description: Commands to change data
  - name: users
    description: Operations available to regular users
paths:
  /dologin:
    post:
      tags:
        - users
      summary: login a user
      operationId: doLogin
      description: Login a user
      responses:
        '303':
          description: user logged in
          content:
            text/plain:
              schema:
                type: string
                example: 
        '401':
          description: email or password do not match
        '400':
          description: malformed request body
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
        description: user credentials and redirect URL

  /createuser:
    post:
      tags:
        - admins
        - commands
      summary: create a user
      operationId: createUser
      description: Create a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserParams'
        description: parameter for the create user command
      responses:
        '201':
          description: user created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResult'
        '400':
          description: malformed request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResult'

components:
  schemas:
    CreateUserParams:
      type: object
      required:
        - email
        - password
      properties:
        givenname:
          type: string
          example: John
        lastname:
          type: string
          example: Doe
        email:
          type: string
          format: email
          example: johndoe@mail.com
        password:
          type: string
          format: password
          example: password
    CommandResult:
      type: object
      properties:
        userId:
          type: string
          example: U000000001
        error:
          type: object
          required:
            - code
            - locale
            - message
          properties:
            code:
              type: string
              example: E1337
            locale:
              type: string
              example: en
            message:
              type: string
              example: User already exists
    Credentials:
      type: object
      required:
        - email
        - password
        - redirectUrl
      properties:
        email:
          type: string
          format: email
          example: johndoe@mail.com
        password:
          type: string
          example: password
        redirectUrl:
          type: string
          format: uri
          example: https://user-management.service.com