openapi: 3.0.0
servers:
  - description: User Management and Identity Provider
    url: /v1
info:
  description: This is the API for the user management and identity provider
  version: "1"
  title: User Management Service
  contact:
    name: Thomas Bonk
    email: thomas@meandmymac.de
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: commands
    description: Commands to change data
  - name: users
    description: Operations available to regular users

paths:
  /authenticate:
    post:
      tags:
        - users
      summary: Login a user
      operationId: authenticate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
        description: user credentials and redirect URL
      responses:
        '303':
          description: user logged in
        '401':
          description: email or password do not match
        '400':
          description: malformed request body

  /createuser:
    post:
      tags:
        - commands
      summary: Create a user
      operationId: createUser
      description: At least the email address and a temporary password must be given.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserParams'
        description: parameter for the create user command
      responses:
        '201':
          description: user created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResult'
        '400':
          description: malformed request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResult'
                
  /changeusername:
    post:
      tags:
        - commands
      summary: Change the name of the user
      description: Only the attributes that are given in request are changed.
      operationId: changeUserName
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeUsernameParams'
        description: parameter for the change user name command
      responses:
        '202':
          description: user change request accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResult'
        '400':
          description: malformed request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResult'

components:
  schemas:
    CreateUserParams:
      type: object
      required:
        - email
        - password
      properties:
        givenname:
          type: string
          example: John
        lastname:
          type: string
          example: Doe
        email:
          type: string
          format: email
          example: johndoe@mail.com
        password:
          type: string
          format: password
          example: password
    ChangeUsernameParams:
      type: object
      properties:
        givenname:
          type: string
          example: John
        lastname:
          type: string
          example: Doe
    CommandResult:
      type: object
      properties:
        userId:
          type: string
          example: U000000001
        error:
          type: object
          required:
            - code
            - locale
            - message
          properties:
            code:
              type: string
              example: E1337
            locale:
              type: string
              example: en
            message:
              type: string
              example: User already exists
    Credentials:
      type: object
      required:
        - email
        - password
        - redirectUrl
      properties:
        email:
          type: string
          format: email
          example: johndoe@mail.com
        password:
          type: string
          example: password
        redirectUrl:
          type: string
          format: uri
          example: https://user-management.service.com